apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.repoUrl | parseRepoUrl | pick('owner') }}/${{values.name}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - documentation
    - mkdocs
    - h1-foundation
spec:
  type: documentation
  lifecycle: ${{values.lifecycle}}
  owner: ${{values.owner}}
  system: ${{values.system}}
