# =============================================================================
# CLUSTER SECRET STORE - AZURE KEY VAULT
# =============================================================================
#
# ClusterSecretStore for syncing secrets from Azure Key Vault to Kubernetes.
# Uses Workload Identity for authentication (no credentials needed).
#
# Prerequisites:
#   - External Secrets Operator installed
#   - Workload Identity configured on AKS
#   - Managed Identity with Key Vault access
#
# Usage:
#   Reference this store in ExternalSecret resources:
#   spec:
#     secretStoreRef:
#       kind: ClusterSecretStore
#       name: azure-keyvault
#
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
  labels:
    app.kubernetes.io/name: azure-keyvault-store
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: platform-security
    platform.three-horizons/tier: h1-foundation
spec:
  provider:
    azurekv:
      # Authentication method: Workload Identity (recommended)
      authType: WorkloadIdentity

      # Key Vault URL - substitute with actual vault URL
      # Format: https://<vault-name>.vault.azure.net/
      vaultUrl: "${KEY_VAULT_URL}"

      # Azure tenant ID
      tenantId: "${AZURE_TENANT_ID}"

      # Service account for Workload Identity
      serviceAccountRef:
        name: external-secrets-controller
        namespace: external-secrets

---
# =============================================================================
# PLATFORM SECRETS - EXAMPLE EXTERNAL SECRET
# =============================================================================
#
# Example ExternalSecret that syncs platform secrets from Key Vault.
# Modify the remoteRef keys to match your Key Vault secret names.
#
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-secrets
    app.kubernetes.io/component: secrets
spec:
  # How often to sync secrets from Key Vault
  refreshInterval: 1h

  # Reference to the ClusterSecretStore
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault

  # Target Kubernetes secret configuration
  target:
    name: platform-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets

  # Secret data mapping
  data:
    # GitHub credentials
    - secretKey: github-token
      remoteRef:
        key: github-pat
        property: value

    # ArgoCD admin password
    - secretKey: argocd-admin-password
      remoteRef:
        key: argocd-admin-password
        property: value

    # Container registry credentials
    - secretKey: acr-password
      remoteRef:
        key: acr-password
        property: value

---
# =============================================================================
# RHDH SECRETS - BACKSTAGE/RHDH CONFIGURATION
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
  namespace: rhdh
  labels:
    app.kubernetes.io/name: rhdh-secrets
    app.kubernetes.io/component: developer-hub
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault

  target:
    name: rhdh-secrets
    creationPolicy: Owner

  data:
    # GitHub OAuth for RHDH
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: rhdh-github-client-id

    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: rhdh-github-client-secret

    # Backend secret for session management
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: rhdh-backend-secret

    # PostgreSQL connection string
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: rhdh-postgres-password

---
# =============================================================================
# OBSERVABILITY SECRETS - GRAFANA/PROMETHEUS
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: observability-secrets
  namespace: observability
  labels:
    app.kubernetes.io/name: observability-secrets
    app.kubernetes.io/component: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault

  target:
    name: observability-secrets
    creationPolicy: Owner

  data:
    # Grafana admin password
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password

    # Azure Monitor integration
    - secretKey: azure-client-secret
      remoteRef:
        key: azure-monitor-client-secret

---
# =============================================================================
# DATABASE SECRETS - POSTGRESQL
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secrets
  namespace: databases
  labels:
    app.kubernetes.io/name: database-secrets
    app.kubernetes.io/component: database
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault

  target:
    name: postgresql-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Connection string format for applications
        connection-string: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:5432/{{ .database }}?sslmode=require"

  data:
    - secretKey: username
      remoteRef:
        key: postgresql-admin-username

    - secretKey: password
      remoteRef:
        key: postgresql-admin-password

    - secretKey: host
      remoteRef:
        key: postgresql-host

    - secretKey: database
      remoteRef:
        key: postgresql-database

---
# =============================================================================
# AI FOUNDRY SECRETS - AZURE OPENAI
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-foundry-secrets
  namespace: ai-foundry
  labels:
    app.kubernetes.io/name: ai-foundry-secrets
    app.kubernetes.io/component: ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault

  target:
    name: azure-openai-credentials
    creationPolicy: Owner

  data:
    # Azure OpenAI API Key
    - secretKey: AZURE_OPENAI_API_KEY
      remoteRef:
        key: azure-openai-api-key

    # Azure OpenAI Endpoint
    - secretKey: AZURE_OPENAI_ENDPOINT
      remoteRef:
        key: azure-openai-endpoint

    # Azure AI Search Key
    - secretKey: AZURE_SEARCH_API_KEY
      remoteRef:
        key: azure-search-api-key
