-- PostgreSQL initialization script for ${{ values.name }}
-- Generated by Three Horizons Golden Path template

CREATE DATABASE ${{ values.databaseName | default(values.name | replace("-", "_")) }};

\c ${{ values.databaseName | default(values.name | replace("-", "_")) }}

-- Create application schema
CREATE SCHEMA IF NOT EXISTS app;

-- Create base tables
CREATE TABLE IF NOT EXISTS app.migrations (
    id SERIAL PRIMARY KEY,
    version VARCHAR(50) NOT NULL,
    description VARCHAR(200),
    applied_at TIMESTAMP DEFAULT NOW()
);

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE ${{ values.databaseName | default(values.name | replace("-", "_")) }} TO ${{ values.databaseName | default(values.name | replace("-", "_")) }}_user;
GRANT USAGE ON SCHEMA app TO ${{ values.databaseName | default(values.name | replace("-", "_")) }}_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA app TO ${{ values.databaseName | default(values.name | replace("-", "_")) }}_user;
