# =============================================================================
# THREE HORIZONS ACCELERATOR - GOLDEN PATHS CATALOG
# =============================================================================
#
# Root catalog file for RHDH to discover all Golden Path templates.
# This file is configured in RHDH values.yaml under catalog.locations.
#
# =============================================================================

apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: three-horizons-golden-paths
  title: Three Horizons Golden Paths
  description: |
    Software templates for the Three Horizons Accelerator.
    Includes Foundation (H1), Enhancement (H2), and Innovation (H3) templates.
  annotations:
    backstage.io/techdocs-entity: location:default/three-horizons-golden-paths
  tags:
    - golden-paths
    - templates
    - three-horizons
spec:
  type: url
  targets:
    # ==========================================================================
    # H1 FOUNDATION TEMPLATES (6)
    # ==========================================================================
    - ./h1-foundation/basic-cicd/template.yaml
    - ./h1-foundation/documentation-site/template.yaml
    - ./h1-foundation/infrastructure-provisioning/template.yaml
    - ./h1-foundation/new-microservice/template.yaml
    - ./h1-foundation/security-baseline/template.yaml
    - ./h1-foundation/web-application/template.yaml

    # ==========================================================================
    # H2 ENHANCEMENT TEMPLATES (9)
    # ==========================================================================
    - ./h2-enhancement/ado-to-github-migration/template.yaml
    - ./h2-enhancement/api-gateway/template.yaml
    - ./h2-enhancement/api-microservice/template.yaml
    - ./h2-enhancement/batch-job/template.yaml
    - ./h2-enhancement/data-pipeline/template.yaml
    - ./h2-enhancement/event-driven-microservice/template.yaml
    - ./h2-enhancement/gitops-deployment/template.yaml
    - ./h2-enhancement/microservice/template.yaml
    - ./h2-enhancement/reusable-workflows/template.yaml

    # ==========================================================================
    # H3 INNOVATION TEMPLATES (7)
    # ==========================================================================
    - ./h3-innovation/ai-evaluation-pipeline/template.yaml
    - ./h3-innovation/copilot-extension/template.yaml
    - ./h3-innovation/foundry-agent/template.yaml
    - ./h3-innovation/mlops-pipeline/template.yaml
    - ./h3-innovation/multi-agent-system/template.yaml
    - ./h3-innovation/rag-application/template.yaml
    - ./h3-innovation/sre-agent-integration/template.yaml

---

# =============================================================================
# SYSTEM DEFINITION
# =============================================================================

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: three-horizons-accelerator
  title: Three Horizons Accelerator
  description: |
    Internal Developer Platform accelerator for enterprise cloud adoption.
    Built on Red Hat Developer Hub, GitHub, and Azure.
  annotations:
    backstage.io/techdocs-ref: dir:../docs
  links:
    - url: https://github.com/${GITHUB_ORG}/three-horizons-accelerator
      title: GitHub Repository
      icon: github
    - url: https://developer.${DNS_ZONE_NAME}
      title: Developer Hub
      icon: dashboard
  tags:
    - platform
    - accelerator
    - three-horizons
spec:
  owner: platform-engineering
  domain: platform

---

# =============================================================================
# DOMAIN DEFINITION
# =============================================================================

apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: platform
  title: Platform Engineering
  description: |
    Platform capabilities and internal developer tools.
spec:
  owner: platform-engineering
