apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.repoUrl | parseRepoUrl | pick('owner') }}/${{values.name}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - copilot
    - ai
    - github
    - extension
    - h3-innovation
spec:
  type: service
  lifecycle: ${{values.lifecycle}}
  owner: ${{values.owner}}
  system: ${{values.system}}
